## RabbitMQ main configuration for Docker
## Load definitions (users, vhosts, permissions) from definitions.json
management.load_definitions = /etc/rabbitmq/.definitions.json

# (optional) tune listeners, heartbeats etc here if needed
